// Package k0s implements join.ClusterJoinProvider for k0s.
//
// Confirmed by reading k0s's own source (pkg/token/{kubeconfig,manager,joinencode}.go):
// a k0s join token is nothing k0s-proprietary -- it's a standard
// Kubernetes bootstrap-token Secret (the same kubeadm-style mechanism
// documented at https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/),
// wrapped in a kubeconfig (Server=the cluster's own API address,
// CertificateAuthorityData=the cluster CA, AuthInfo="kubelet-bootstrap",
// Token=<token-id>.<token-secret>), then gzip+base64 encoded. This
// means a join token can be minted entirely through the Kubernetes API
// this operator already has -- no SSH to a control-plane node needed.
package k0s

import (
	"bytes"
	"compress/gzip"
	"context"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"time"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/clientcmd"
	clientcmdapi "k8s.io/client-go/tools/clientcmd/api"
)

// tokenChars matches kubeadm/k0s's own bootstrap-token character set:
// lowercase alphanumeric only (RFC: [a-z0-9]).
const tokenChars = "0123456789abcdefghijklmnopqrstuvwxyz"

// Provider implements join.ClusterJoinProvider for k0s.
type Provider struct {
	Client kubernetes.Interface
	// APIAddress is this cluster's own API server address as reached
	// from a newly-joining node (e.g. "https://10.101.0.1:6443" -- the
	// VIP reachable once the node's WireGuard tunnel is up, not a
	// tailnet/admin-only address).
	APIAddress string
	// TTL is how long the minted token remains valid. Short-lived by
	// design (matches this project's existing "2h, not 1 year"
	// precedent) -- the exposure window this protects against is the
	// few minutes between instance launch and first join, not
	// indefinite credential validity.
	TTL time.Duration
}

// JoinValues implements join.ClusterJoinProvider.
func (p *Provider) JoinValues(ctx context.Context) (map[string]any, error) {
	tokenID, err := randomToken(6)
	if err != nil {
		return nil, fmt.Errorf("generating token id: %w", err)
	}
	tokenSecret, err := randomToken(16)
	if err != nil {
		return nil, fmt.Errorf("generating token secret: %w", err)
	}

	expiry := time.Now().Add(p.TTL).UTC()
	secret := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "bootstrap-token-" + tokenID,
			Namespace: metav1.NamespaceSystem,
		},
		Type: corev1.SecretType("bootstrap.kubernetes.io/token"),
		StringData: map[string]string{
			"description":                    "Worker bootstrap token generated by cloud-provisioning",
			"token-id":                       tokenID,
			"token-secret":                   tokenSecret,
			"expiration":                     expiry.Format(time.RFC3339),
			"usage-bootstrap-authentication": "true",
		},
	}
	if _, err := p.Client.CoreV1().Secrets(metav1.NamespaceSystem).Create(ctx, secret, metav1.CreateOptions{}); err != nil {
		return nil, fmt.Errorf("creating bootstrap-token secret: %w", err)
	}

	caCert, err := p.clusterCACert(ctx)
	if err != nil {
		return nil, fmt.Errorf("reading cluster CA: %w", err)
	}

	k0sVersion, err := p.introspectK0sVersion(ctx)
	if err != nil {
		return nil, fmt.Errorf("introspecting k0s version: %w", err)
	}

	kubeconfig, err := buildKubeconfig(p.APIAddress, caCert, tokenID+"."+tokenSecret)
	if err != nil {
		return nil, fmt.Errorf("building bootstrap kubeconfig: %w", err)
	}

	joinToken, err := gzipBase64(kubeconfig)
	if err != nil {
		return nil, fmt.Errorf("encoding join token: %w", err)
	}

	return map[string]any{
		"joinToken":  joinToken,
		"k0sVersion": k0sVersion,
	}, nil
}

// clusterCACert reads the cluster CA from the kube-root-ca.crt
// ConfigMap Kubernetes projects into every namespace -- a standard
// built-in mechanism, not anything k0s- or cloud-provisioning-specific.
func (p *Provider) clusterCACert(ctx context.Context) ([]byte, error) {
	cm, err := p.Client.CoreV1().ConfigMaps(metav1.NamespaceSystem).Get(ctx, "kube-root-ca.crt", metav1.GetOptions{})
	if err != nil {
		return nil, err
	}
	caCert, ok := cm.Data["ca.crt"]
	if !ok {
		return nil, fmt.Errorf("kube-root-ca.crt configmap has no ca.crt key")
	}
	return []byte(caCert), nil
}

// introspectK0sVersion reads the running k0s version off any existing
// Node's own status, rather than hardcoding it -- so this stays
// correct across upgrades without a code change.
func (p *Provider) introspectK0sVersion(ctx context.Context) (string, error) {
	nodes, err := p.Client.CoreV1().Nodes().List(ctx, metav1.ListOptions{Limit: 1})
	if err != nil {
		return "", err
	}
	if len(nodes.Items) == 0 {
		return "", fmt.Errorf("no nodes found to introspect k0s version from")
	}
	// e.g. "v1.36.2+k0s" -> "v1.36.2+k0s.0" is the release-asset naming;
	// k0s's own kubeletVersion already carries the "+k0s" suffix the
	// get.k0s.sh installer's K0S_VERSION expects.
	return nodes.Items[0].Status.NodeInfo.KubeletVersion, nil
}

func buildKubeconfig(server string, caCert []byte, token string) ([]byte, error) {
	const contextName = "k0s"
	const userName = "kubelet-bootstrap"
	return clientcmd.Write(clientcmdapi.Config{
		Clusters: map[string]*clientcmdapi.Cluster{contextName: {
			Server:                   server,
			CertificateAuthorityData: caCert,
		}},
		Contexts: map[string]*clientcmdapi.Context{contextName: {
			Cluster:  contextName,
			AuthInfo: userName,
		}},
		CurrentContext: contextName,
		AuthInfos: map[string]*clientcmdapi.AuthInfo{userName: {
			Token: token,
		}},
	})
}

// gzipBase64 matches k0s's own JoinEncode exactly (pkg/token/joinencode.go):
// gzip best-compression, then standard base64.
func gzipBase64(data []byte) (string, error) {
	var buf bytes.Buffer
	gz, err := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	if err != nil {
		return "", err
	}
	if _, err := gz.Write(data); err != nil {
		return "", err
	}
	if err := gz.Close(); err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(buf.Bytes()), nil
}

func randomToken(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	out := make([]byte, n)
	for i, v := range b {
		out[i] = tokenChars[int(v)%len(tokenChars)]
	}
	return string(out), nil
}
