// Package k0s implements join.ClusterJoinProvider for k0s.
//
// Confirmed by reading k0s's own source (pkg/token/{kubeconfig,manager,joinencode}.go):
// a k0s join token is nothing k0s-proprietary -- it's a standard
// Kubernetes bootstrap-token Secret (the same kubeadm-style mechanism
// documented at https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/),
// wrapped in a kubeconfig (Server=the cluster's own API address,
// CertificateAuthorityData=the cluster CA, AuthInfo="kubelet-bootstrap",
// Token=<token-id>.<token-secret>), then gzip+base64 encoded. This
// means a join token can be minted entirely through the Kubernetes API
// this operator already has -- no SSH to a control-plane node needed.
package k0s

import (
	"bytes"
	"compress/gzip"
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/clientcmd"
	clientcmdapi "k8s.io/client-go/tools/clientcmd/api"
)

// tokenChars matches kubeadm/k0s's own bootstrap-token character set:
// lowercase alphanumeric only (RFC: [a-z0-9]).
const tokenChars = "0123456789abcdefghijklmnopqrstuvwxyz"

// Provider implements join.ClusterJoinProvider for k0s.
type Provider struct {
	Client kubernetes.Interface
	// APIAddress is this cluster's own API server address as reached
	// from a newly-joining node (e.g. "https://10.101.0.1:6443" -- the
	// VIP reachable once the node's WireGuard tunnel is up, not a
	// tailnet/admin-only address).
	APIAddress string
	// TTL is how long the minted token remains valid. Short-lived by
	// design (matches this project's existing "2h, not 1 year"
	// precedent) -- the exposure window this protects against is the
	// few minutes between instance launch and first join, not
	// indefinite credential validity.
	TTL time.Duration

	// GitHubReleasesAPI is the base URL for k0s's GitHub releases API,
	// overridable for tests (an httptest.Server) -- defaults to the
	// real API when empty. See resolveK0sReleaseTag: this exists
	// because Node.status.nodeInfo.KubeletVersion (e.g. "v1.36.2+k0s")
	// is NOT the actual release tag/asset name k0s publishes
	// ("v1.36.2+k0s.0") -- confirmed live: using the bare kubelet
	// version as get.k0s.sh's K0S_VERSION 404s, since neither the
	// release tag nor the release asset filename ever omit the
	// trailing build-counter suffix.
	GitHubReleasesAPI string
}

const defaultGitHubReleasesAPI = "https://api.github.com/repos/k0sproject/k0s/releases"

// JoinValues implements join.ClusterJoinProvider.
func (p *Provider) JoinValues(ctx context.Context) (map[string]any, error) {
	tokenID, err := randomToken(6)
	if err != nil {
		return nil, fmt.Errorf("generating token id: %w", err)
	}
	tokenSecret, err := randomToken(16)
	if err != nil {
		return nil, fmt.Errorf("generating token secret: %w", err)
	}

	expiry := time.Now().Add(p.TTL).UTC()
	secret := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "bootstrap-token-" + tokenID,
			Namespace: metav1.NamespaceSystem,
		},
		Type: corev1.SecretType("bootstrap.kubernetes.io/token"),
		StringData: map[string]string{
			"description":                    "Worker bootstrap token generated by cloud-provisioning",
			"token-id":                       tokenID,
			"token-secret":                   tokenSecret,
			"expiration":                     expiry.Format(time.RFC3339),
			"usage-bootstrap-authentication": "true",
		},
	}
	if _, err := p.Client.CoreV1().Secrets(metav1.NamespaceSystem).Create(ctx, secret, metav1.CreateOptions{}); err != nil {
		return nil, fmt.Errorf("creating bootstrap-token secret: %w", err)
	}

	caCert, err := p.clusterCACert(ctx)
	if err != nil {
		return nil, fmt.Errorf("reading cluster CA: %w", err)
	}

	k0sVersion, err := p.introspectK0sVersion(ctx)
	if err != nil {
		return nil, fmt.Errorf("introspecting k0s version: %w", err)
	}

	kubeconfig, err := buildKubeconfig(p.APIAddress, caCert, tokenID+"."+tokenSecret)
	if err != nil {
		return nil, fmt.Errorf("building bootstrap kubeconfig: %w", err)
	}

	joinToken, err := gzipBase64(kubeconfig)
	if err != nil {
		return nil, fmt.Errorf("encoding join token: %w", err)
	}

	return map[string]any{
		"joinToken":  joinToken,
		"k0sVersion": k0sVersion,
	}, nil
}

// clusterCACert reads the cluster CA from the kube-root-ca.crt
// ConfigMap Kubernetes projects into every namespace -- a standard
// built-in mechanism, not anything k0s- or cloud-provisioning-specific.
func (p *Provider) clusterCACert(ctx context.Context) ([]byte, error) {
	cm, err := p.Client.CoreV1().ConfigMaps(metav1.NamespaceSystem).Get(ctx, "kube-root-ca.crt", metav1.GetOptions{})
	if err != nil {
		return nil, err
	}
	caCert, ok := cm.Data["ca.crt"]
	if !ok {
		return nil, fmt.Errorf("kube-root-ca.crt configmap has no ca.crt key")
	}
	return []byte(caCert), nil
}

// introspectK0sVersion reads the running k0s version off any existing
// Node's own status, rather than hardcoding it -- so this stays
// correct across upgrades without a code change. The Node's
// KubeletVersion (e.g. "v1.36.2+k0s") is only a prefix of the actual
// release tag/asset name k0s publishes (e.g. "v1.36.2+k0s.0");
// resolveK0sReleaseTag turns it into the real, download-able tag.
func (p *Provider) introspectK0sVersion(ctx context.Context) (string, error) {
	nodes, err := p.Client.CoreV1().Nodes().List(ctx, metav1.ListOptions{Limit: 1})
	if err != nil {
		return "", err
	}
	if len(nodes.Items) == 0 {
		return "", fmt.Errorf("no nodes found to introspect k0s version from")
	}
	kubeletVersion := nodes.Items[0].Status.NodeInfo.KubeletVersion
	return resolveK0sReleaseTag(ctx, p.githubReleasesAPI(), kubeletVersion)
}

func (p *Provider) githubReleasesAPI() string {
	if p.GitHubReleasesAPI != "" {
		return p.GitHubReleasesAPI
	}
	return defaultGitHubReleasesAPI
}

type githubRelease struct {
	TagName string `json:"tag_name"`
}

// resolveK0sReleaseTag turns a bare kubelet version (e.g.
// "v1.36.2+k0s", what Node.status.nodeInfo.KubeletVersion actually
// reports) into the real k0s release tag (e.g. "v1.36.2+k0s.0") that
// exists as a downloadable GitHub release/asset -- confirmed live
// against k0sproject/k0s's actual releases: every real tag carries a
// trailing numeric build counter the bare kubelet version never
// includes, and get.k0s.sh's installer does no fuzzy matching of its
// own (a bare "v1.36.2+k0s" 404s outright).
//
// Deliberately does not stop at the first match (e.g. a direct
// "<version>.0" lookup): k0sproject/k0s has genuinely published more
// than one release for the same k8s version (confirmed live:
// v1.35.1+k0s.0 AND v1.35.1+k0s.1 both exist, non-draft, non-prerelease)
// -- a later counter is a re-release of the same k8s version, so it's
// the one that should be used. Since the bare kubelet version can't
// distinguish these, every release is listed and the highest counter
// matching this exact version prefix wins.
func resolveK0sReleaseTag(ctx context.Context, releasesAPI, kubeletVersion string) (string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, releasesAPI+"?per_page=100", nil)
	if err != nil {
		return "", err
	}
	best := ""
	bestN := -1
	for page := 1; ; page++ {
		req.URL.RawQuery = fmt.Sprintf("per_page=100&page=%d", page)
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			return "", fmt.Errorf("listing k0s releases: %w", err)
		}
		var releases []githubRelease
		decodeErr := json.NewDecoder(resp.Body).Decode(&releases)
		resp.Body.Close()
		if resp.StatusCode != http.StatusOK {
			return "", fmt.Errorf("listing k0s releases: unexpected status %d", resp.StatusCode)
		}
		if decodeErr != nil {
			return "", fmt.Errorf("decoding k0s releases: %w", decodeErr)
		}
		if len(releases) == 0 {
			break
		}
		for _, r := range releases {
			suffix, ok := strings.CutPrefix(r.TagName, kubeletVersion+".")
			if !ok {
				continue
			}
			n, err := strconv.Atoi(suffix)
			if err != nil {
				continue
			}
			if n > bestN {
				bestN = n
				best = r.TagName
			}
		}
	}
	if best == "" {
		return "", fmt.Errorf("no k0s release found matching kubelet version %q (checked every release tag with that prefix)", kubeletVersion)
	}
	return best, nil
}

func buildKubeconfig(server string, caCert []byte, token string) ([]byte, error) {
	const contextName = "k0s"
	const userName = "kubelet-bootstrap"
	return clientcmd.Write(clientcmdapi.Config{
		Clusters: map[string]*clientcmdapi.Cluster{contextName: {
			Server:                   server,
			CertificateAuthorityData: caCert,
		}},
		Contexts: map[string]*clientcmdapi.Context{contextName: {
			Cluster:  contextName,
			AuthInfo: userName,
		}},
		CurrentContext: contextName,
		AuthInfos: map[string]*clientcmdapi.AuthInfo{userName: {
			Token: token,
		}},
	})
}

// gzipBase64 matches k0s's own JoinEncode exactly (pkg/token/joinencode.go):
// gzip best-compression, then standard base64.
func gzipBase64(data []byte) (string, error) {
	var buf bytes.Buffer
	gz, err := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	if err != nil {
		return "", err
	}
	if _, err := gz.Write(data); err != nil {
		return "", err
	}
	if err := gz.Close(); err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(buf.Bytes()), nil
}

func randomToken(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	out := make([]byte, n)
	for i, v := range b {
		out[i] = tokenChars[int(v)%len(tokenChars)]
	}
	return string(out), nil
}
