// Package kubeadm implements join.ClusterJoinProvider for
// kubeadm-based control planes (including kind, whose control plane IS
// kubeadm). k0s is one specialization of cluster-join support; this is
// another -- same seam, different credential shape.
//
// A kubeadm worker join needs three things, all mintable through the
// Kubernetes API this operator already has: a standard bootstrap-token
// Secret (with the signing usage, so kubeadm's cluster-info discovery
// can validate), the cluster CA's public-key hash (pinning discovery
// against MITM -- kubeadm's own --discovery-token-ca-cert-hash), and
// the API endpoint the new node should join through.
package kubeadm

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	"encoding/pem"
	"fmt"
	"net/url"
	"time"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
)

const tokenChars = "0123456789abcdefghijklmnopqrstuvwxyz"

// Provider implements join.ClusterJoinProvider for kubeadm.
type Provider struct {
	Client kubernetes.Interface
	// APIAddress is the cluster's API server address as reached from a
	// newly-joining node (e.g. "https://10.2.0.19:6443").
	APIAddress string
	// TTL is how long the minted token remains valid -- short-lived by
	// design, covering the minutes between instance launch and first
	// join, not indefinite credential validity.
	TTL time.Duration
}

// JoinValues implements join.ClusterJoinProvider. Contributed values:
//
//	joinToken         -- "<id>.<secret>", kubeadm's own token format
//	joinEndpoint      -- "host:port" for `kubeadm join <endpoint>`
//	caCertHash        -- "sha256:<hex>" for --discovery-token-ca-cert-hash
//	kubernetesVersion -- from a live node, for installing matching kubelet/kubeadm
func (p *Provider) JoinValues(ctx context.Context) (map[string]any, error) {
	tokenID, err := randomToken(6)
	if err != nil {
		return nil, fmt.Errorf("generating token id: %w", err)
	}
	tokenSecret, err := randomToken(16)
	if err != nil {
		return nil, fmt.Errorf("generating token secret: %w", err)
	}

	expiry := time.Now().Add(p.TTL).UTC()
	secret := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "bootstrap-token-" + tokenID,
			Namespace: metav1.NamespaceSystem,
		},
		Type: corev1.SecretType("bootstrap.kubernetes.io/token"),
		StringData: map[string]string{
			"description":  "Worker bootstrap token generated by cloud-provisioning",
			"token-id":     tokenID,
			"token-secret": tokenSecret,
			"expiration":   expiry.Format(time.RFC3339),
			// Unlike k0s's flow, kubeadm needs BOTH usages: authentication
			// for the bootstrap kubelet client, signing so the
			// cluster-info ConfigMap discovery is JWS-signed with this
			// token (that's what makes `kubeadm join` trust it).
			"usage-bootstrap-authentication": "true",
			"usage-bootstrap-signing":        "true",
			"auth-extra-groups":              "system:bootstrappers:kubeadm:default-node-token",
		},
	}
	if _, err := p.Client.CoreV1().Secrets(metav1.NamespaceSystem).Create(ctx, secret, metav1.CreateOptions{}); err != nil {
		return nil, fmt.Errorf("creating bootstrap-token secret: %w", err)
	}

	caHash, err := p.clusterCAHash(ctx)
	if err != nil {
		return nil, fmt.Errorf("computing cluster CA hash: %w", err)
	}

	version, err := p.kubernetesVersion(ctx)
	if err != nil {
		return nil, fmt.Errorf("introspecting kubernetes version: %w", err)
	}

	endpoint, err := hostPort(p.APIAddress)
	if err != nil {
		return nil, err
	}

	return map[string]any{
		"joinToken":         tokenID + "." + tokenSecret,
		"joinEndpoint":      endpoint,
		"caCertHash":        caHash,
		"kubernetesVersion": version,
	}, nil
}

// clusterCAHash computes kubeadm's discovery pin: sha256 over the CA
// certificate's Subject Public Key Info (NOT the whole certificate) --
// the exact value `kubeadm token create --print-join-command` emits,
// per kubeadm's own pubkeypin package. CA read from the
// kube-root-ca.crt ConfigMap Kubernetes projects into every namespace.
func (p *Provider) clusterCAHash(ctx context.Context) (string, error) {
	cm, err := p.Client.CoreV1().ConfigMaps(metav1.NamespaceSystem).Get(ctx, "kube-root-ca.crt", metav1.GetOptions{})
	if err != nil {
		return "", err
	}
	caPEM, ok := cm.Data["ca.crt"]
	if !ok {
		return "", fmt.Errorf("kube-root-ca.crt configmap has no ca.crt key")
	}
	block, _ := pem.Decode([]byte(caPEM))
	if block == nil {
		return "", fmt.Errorf("kube-root-ca.crt is not PEM")
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return "", fmt.Errorf("parsing cluster CA certificate: %w", err)
	}
	sum := sha256.Sum256(cert.RawSubjectPublicKeyInfo)
	return "sha256:" + hex.EncodeToString(sum[:]), nil
}

// kubernetesVersion reads the cluster version off any existing Node.
func (p *Provider) kubernetesVersion(ctx context.Context) (string, error) {
	nodes, err := p.Client.CoreV1().Nodes().List(ctx, metav1.ListOptions{Limit: 1})
	if err != nil {
		return "", err
	}
	if len(nodes.Items) == 0 {
		return "", fmt.Errorf("no nodes found to introspect the kubernetes version from")
	}
	return nodes.Items[0].Status.NodeInfo.KubeletVersion, nil
}

// hostPort extracts "host:port" from the API address URL -- kubeadm
// join takes a bare endpoint, not a URL.
func hostPort(apiAddress string) (string, error) {
	u, err := url.Parse(apiAddress)
	if err != nil || u.Host == "" {
		return "", fmt.Errorf("APIAddress %q is not a URL with a host", apiAddress)
	}
	host := u.Host
	if u.Port() == "" {
		host += ":6443"
	}
	return host, nil
}

func randomToken(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	out := make([]byte, n)
	for i, v := range b {
		out[i] = tokenChars[int(v)%len(tokenChars)]
	}
	return string(out), nil
}
