image:
  pullPolicy: Never
nodeSelector:
  kubernetes.io/hostname: w2
resources:
  operator:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 512Mi
  metricServer:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 512Mi
  webhooks:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 512Mi
